### ISSUE TITLE
Error when test ends up by the suffix Jar

### ISSUE THREAD

**Issue by iemejia** [Zlika/reproducible-build-maven-plugin#6]
I am trying to use this plugin (btw, excellent job and thanks a lot for creating it) to make the Apache Beam builds reproducible and I just found an issue because the plugin does not detect correctly one case.
```
Caused by: java.io.FileNotFoundException: /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_MavenInstall/runners/apex/target/testCreateJar (Is a directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:213)
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:192)
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:153)
	at io.github.zlika.reproducible.ZipStripper.strip(ZipStripper.java:62)
	at io.github.zlika.reproducible.StripJarMojo.strip(StripJarMojo.java:81)
```
It seems it does not check if the matched path is a directory or not and it tries to unzip it which in the case of a directory will fail.

**Comment by Zlika** [comment]
Thank you for reporting this bug. I will fix it when I'm back from holidays.

**Comment by Zlika** [comment]
Could you test the HEAD version and check that the problem is solved? Thanks.

**Comment by Zlika** [comment]
Version 0.3 deployed on Maven Central.

**Comment by iemejia** [comment]
Thanks a lot, I just wanted to confirm you that everything works as intended with the released version (0.3), Thanks.
Have you tried to get your plugin or at least the jar cleaning parts into Apache?, it would be nice to have it there.

**Comment by Zlika** [comment]
Thanks for the feedback.
I think the right place for this feature should in Maven itself (or more precisely inside some of its core plugins). I gave a talk at Devoxx France 2016 on reproducible builds with Maven (cf. http://zlika.github.io/presentations/devoxx_fr_2016/reproducible-builds/slides_en.html) and I had the opportunity to talk with an Apache guy working on Maven who adviced me to open an issue on this subject on the Maven Jira. It's still on my todo list though :-(

**Comment by psacc** [comment]
I took the liberty to create https://issues.apache.org/jira/browse/MNG-6276 hoping that helps moving forward reproducibility support in maven.
